---
title: "ABC Beverage"
author: "Tony, Shariq, Seung-Min"
date: "28 April 2024"
format:
  html:
    theme: cosmo
    toc: true
    number_sections: true
---

```{r load_libraries, message=FALSE, warning=FALSE}
library(readxl)
library(dplyr)
# library(caret)  
# library(party) 
# library(pls)  
# library(pdp) 
# library(Cubist)
# library(xgboost)
# library(randomForest)
# options(scipen=999)
# library(earth)
# library(Formula)
# library(plotmo)
# library(plotrix)
# library(DiagrammeR)
# library(AppliedPredictiveModeling)
```

#  Explore data

stuff

## load and prepare

stuff

```{r loadData}
github_url <- "https://github.com/tonythor/abc-beverage/raw/develop/data/"
train_fn <- "StudentData_Training.xlsx"
test_fn <- "StudentEvaluation_Test.xlsx"

train_url <- paste0(github_url, train_fn) 
test_url <- paste0(github_url, test_fn)

download.file(train_url, destfile = train_fn, mode = "wb")
download.file(test_url, destfile = test_fn, mode = "wb")
train <- read_excel(train_fn)
test <- read_excel(test_fn)

file.remove(c(train_fn, test_fn))
```


Lets do some fancy stuff here.

